_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 100

precision: 16
deterministic: False
accelerator: gpu
devices: [1]
num_nodes: 1