_target_: src.models.smp_module.SmpModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

arch_name: "UnetPlusPlus"
encoder_name: "timm-mobilenetv3_small_100"
loss_type: 'mse'
module_type: 'base'
activation: 'sigmoid'