# @package _global_

defaults:
  - _self_
  - datamodule: smp.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: smp.yaml
  - logger: null
  - trainer: gpu.yaml
  - callbacks: test.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "/opt/ml/aistage_smp/logs/train/runs/base/UnetPlusPlus/timm-mobilenetv3_small_100/2022-12-19_20-21-24/checkpoints/epoch_004.ckpt"
